import { StringUtils } from '@lib';

[
  'aceptáis',
  'acepté',
  'aceptaste',
  'aceptó',
  'aceptamos',
  'aceptasteis',
  'aceptaron',
  'aceptaré',
  'aceptarás',
  'aceptará',
  'aceptaremos',
  'aceptaréis',
  'aceptarán',
  'consentís',
  'consentí',
  'consentiste',
  'consintió',
  'consentimos',
  'consentisteis',
  'consintieron',

  'investigué',
  'investigaste',
  'investigó',
  'investigamos',
  'investigasteis',
  'investigaré',
  'investigarás',
  'investigará',
  'investigaremos',
  'investigaréis',
  'investigarán',
].map((x) => console.log(x, StringUtils.removeAccents(x)));
